name: build-windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build exe with yao-pkg (Node 20, explicit entry, no bytecode)
        shell: pwsh
        run: |
          npx -y @yao-pkg/pkg@latest --version
          $env:PKG_DEBUG = "1"
          npx -y @yao-pkg/pkg@latest index.js -t node20-win-x64 --no-bytecode -o .\dist\memescanner-win-x64.exe

      - name: List dist
        shell: pwsh
        run: |
          Get-ChildItem -Recurse .\dist
          if (-not (Test-Path .\dist\memescanner-win-x64.exe)) { throw "exe not found" }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: memescanner-win-x64
          path: dist/memescanner-win-x64.exe
          retention-days: 30

